training:
  epochs: 50
  learning_rate: 0.001
  batch_size: 32
  early_stopping_patience: 5
  device: "cuda"  # ou "auto" pour laisser PyTorch choisir
  scheduler:
    type: "step_lr"
    step_size: 10
    gamma: 0.1
  metrics: ["accuracy", "f1_score"]
  save_best_model: true
